logging: 
  file:
    name: logs/application.log
    path: logs/
    max-size: 50mb
      
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5level) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %X{userId} %m%n%wEx"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5level ${PID:- } --- [%15.15t] %-40.40logger{39} : %X{userId} %m%n%wEx"
  level:
    root: info
management:
    dynatrace:
      metrics:
        export:
          enabled: true
server:
  ssl:
    enabled: false
  port: 8443
